# AUTO-GENERATED FILE - DO NOT EDIT
# Generated from schema/bundle.schema.json
# Run 'npm run generate:types' to regenerate

# generated by datamodel-codegen:
#   filename:  bundle.schema.json
#   timestamp: 2026-01-26T19:11:41+00:00
#
# Modified for Python 3.8 compatibility

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class TokenCounts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: conint(ge=0)
    output: conint(ge=0)
    cached: conint(ge=0)


class DailyActivity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') = Field(
        ..., description='Date in YYYY-MM-DD format'
    )
    sessions: conint(ge=0)


class Quirks(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interruptCount: conint(ge=0)
    abandonedSessions: conint(ge=0)
    lateNightSessions: conint(ge=0)
    earlyMorningSessions: conint(ge=0)
    weekendPercentage: conint(ge=0, le=100)
    shortestSessionSeconds: conint(ge=0)
    longestStreakDays: conint(ge=0)


class PromptWithContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    prompt: str = Field(..., description='The actual prompt text (truncated if needed)')
    context: Optional[str] = Field(
        None, description='Brief context about why this prompt was selected'
    )


class PolitenessLevel(Enum):
    diplomatic = 'diplomatic'
    direct = 'direct'
    demanding = 'demanding'
    apologetic = 'apologetic'


class CommunicationStyle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    catchphrases: Optional[List[str]] = Field(
        None, description='Unique phrases they repeat'
    )
    signatureOpeners: Optional[List[str]] = Field(
        None, description='How they typically start prompts'
    )
    verbalTics: Optional[List[str]] = Field(
        None, description='Filler words, hedging patterns'
    )
    politenessLevel: Optional[PolitenessLevel] = Field(
        None, description='Overall politeness characterization'
    )
    averagePromptLength: Optional[conint(ge=0)] = Field(
        None, description='Average character length of prompts'
    )
    promptingEvolution: Optional[str] = Field(
        None, description='How their style changed over time'
    )


class Obsessions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    topics: Optional[List[str]] = Field(
        None, description='Technical areas they focus on'
    )
    frequentlyRevisited: Optional[List[str]] = Field(
        None, description='Problems they kept coming back to'
    )
    actualProjects: Optional[List[str]] = Field(
        None, description='What they were actually building (inferred)'
    )


class Contrasts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    shortestEffective: Optional[str] = Field(
        None, description='Shortest prompt that still got results'
    )
    longestRamble: Optional[str] = Field(
        None, description='When they really went off (truncated)'
    )
    politestMoment: Optional[str] = Field(None, description='Most courteous request')
    mostDemanding: Optional[str] = Field(
        None, description='Most direct/demanding request'
    )
    capsLockPrompts: Optional[conint(ge=0)] = Field(
        None, description='Count of prompts that were mostly ALL CAPS'
    )
    vaguePromptCount: Optional[conint(ge=0)] = Field(
        None, description='Count of very short/vague prompts (<30 chars)'
    )
    undoRequests: Optional[conint(ge=0)] = Field(
        None, description='How many times they asked to undo/revert/go back'
    )


class WordCount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    word: str
    count: conint(ge=0)


class PhraseCount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phrase: str
    count: conint(ge=0)


class Stats(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    totalSessions: conint(ge=0)
    totalMessages: conint(ge=0)
    totalTokens: TokenCounts
    totalToolCalls: conint(ge=0)
    toolUsage: Dict[str, int] = Field(
        ..., description='Map of tool name to usage count'
    )
    modelUsage: Dict[str, int] = Field(
        ..., description='Map of model name to token count'
    )
    hourCounts: List[int] = Field(
        ..., description='Session counts by hour (0-23)', max_length=24, min_length=24
    )
    peakHour: conint(ge=0, le=23)
    longestSessionMinutes: conint(ge=0)
    totalMinutes: Optional[conint(ge=0)] = Field(
        None,
        description='Total time across all sessions in minutes (calculated from timestamps)',
    )
    projectCount: conint(ge=0)
    daysActive: conint(ge=0)
    activeDates: Optional[List[DailyActivity]] = Field(
        None, description='Daily activity for contribution grid'
    )


class MemorablePrompts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    funniest: Optional[PromptWithContext] = None
    mostFrustrated: Optional[PromptWithContext] = None
    mostAmbitious: Optional[PromptWithContext] = None
    biggestFacepalm: Optional[PromptWithContext] = None
    mostGrateful: Optional[PromptWithContext] = None
    weirdest: Optional[PromptWithContext] = None
    lateNightRamble: Optional[PromptWithContext] = None


class Insights(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    memorablePrompts: Optional[MemorablePrompts] = None
    communicationStyle: Optional[CommunicationStyle] = None
    obsessions: Optional[Obsessions] = None
    contrasts: Optional[Contrasts] = None
    topWords: Optional[List[WordCount]] = Field(
        None, description='Most meaningful words used'
    )
    topPhrases: Optional[List[PhraseCount]] = Field(
        None, description='Most common meaningful phrases'
    )
    dominantTopics: Optional[List[str]] = Field(
        None,
        description='Primary areas of focus (debugging, frontend, backend, devops, ai, testing, refactoring)',
    )


class AnonymousBundle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stats: Stats
    quirks: Optional[Quirks] = None
    insights: Optional[Insights] = None
    personaId: str = Field(..., description='Persona identifier')
    traits: List[str] = Field(..., description='List of trait keywords')
    promptingStyle: str = Field(..., description='Description of prompting style')
    communicationTone: str = Field(..., description='Description of communication tone')
    funFacts: List[str] = Field(..., description='List of fun facts about usage')
    generatedAt: AwareDatetime = Field(
        ..., description='ISO 8601 timestamp of bundle generation'
    )
